---
- block:

  - name: managing resolv.conf file entries
    template:
      src: "{{ common_resolv_template }}"
      dest: "/etc/resolv.conf"
      owner: root
      group: root
      mode: 0644

  when: common_resolv_enabled
