---

- block:

  # TCP Performance tunning
  - sysctl:
      name: net.core.somaxconn
      value: 1024
      state: present

  # increase the length of the processor input queue
  - sysctl:
      name: net.core.netdev_max_backlog
      value: 30000
      state: present

  # The maximum number of backlogged sockets
  - sysctl:
      name: net.ipv4.tcp_max_syn_backlog
      value: 2048
      state: present

  # 16MB per socket
  - sysctl:
      name: net.core.rmem_max
      value: 16777216
      state: present

  - sysctl:
      name: net.core.wmem_max
      value: 16777216
      state: present

  # Increase the number of outstanding syn requests allowed
  - sysctl:
      name: net.ipv4.tcp_max_syn_backlog
      value: 4096
      state: present

  # Allow The use of syncookies
  - sysctl:
      name: net.ipv4.tcp_syncookies
      value: 1
      state: present

  when: common_sysctl_tweaks_enabled
