etcd_home: "/opt/etcd"
etcd_data_directory: "{{ etcd_home }}/data"

etcd_client_port: "2379"
etcd_peer_port: "2380"

etcd_user:
  id: 30002
  name: dkr-etcd

etcd_docker_image: quay.io/coreos/etcd:v3.4.13

etcd_docker_env:
  ETCD_NAME: "{{ inventory_hostname }}"
  ETCD_DATA_DIR: "/data"
  ETCD_LOGGER: "zap"
  ETCD_LOG_LEVEL: "debug"
  ETCD_LOG_OUTPUTS: "stdout"

  ## listen addresses (bind to all interfaces in docer container)
  # used for peer-tp-peer etcd communication
  ETCD_LISTEN_PEER_URLS: "https://0.0.0.0:2380"
  # used for clients (application) to connect to
  ETCD_LISTEN_CLIENT_URLS: "https://0.0.0.0:2379"

  # etcd peer clustering (static)
  ETCD_INITIAL_ADVERTISE_PEER_URLS: https://{{ inventory_hostname }}:{{ etcd_peer_port | default('2380') }}
  ETCD_INITIAL_CLUSTER: "{% for host in groups['etcd'] | sort() %}{{ host }}=https://{{ host }}:{{ etcd_peer_port | default('2380') }}{% if not loop.last %},{% endif %}{% endfor %}"
  ETCD_INITIAL_CLUSTER_STATE: new
  ETCD_INITIAL_CLUSTER_TOKEN: "oe5lohh1quee9zoomaix7Goh"

  # etcd endpoint that clients (application) talk to
  ETCD_ADVERTISE_CLIENT_URLS:  https://{{ inventory_hostname }}:{{ etcd_client_port | default('2379') }}

  ## TLS settings
  # peer-to-peer TLS
  ETCD_PEER_CLIENT_CERT_AUTH: "{{ etcd_tls_peer_client_auth | string }}"
  ETCD_PEER_TRUSTED_CA_FILE: /etc/tls/peer-ca.pem
  ETCD_PEER_CERT_FILE: /etc/tls/peer-cert.pem
  ETCD_PEER_KEY_FILE: /etc/tls/peer-key.pem
  # client-to-etcd TLS
  ETCD_CLIENT_CERT_AUTH: "{{ etcd_tls_client_auth | string }}"
  ETCD_TRUSTED_CA_FILE: /etc/tls/client-ca.pem
  ETCD_CERT_FILE: /etc/tls/cert.pem
  ETCD_KEY_FILE: /etc/tls/key.pem
