artifacts_dir: "{{ playbook_dir }}/../artifacts"
# default location to place pki
pki_dir: "{{ artifacts_dir }}/pki"
etcd_pki_dir: "{{ pki_dir }}/etcd"
sensu_pki_dir: "{{ pki_dir }}/sensu"

# etcd root CA details (both peer and client)
etcd_root_ca:
  curve: secp521r1
  digest: sha512
  expiration: "+3650d"

# etcd peers
etcd_peer:
  curve: secp256r1
  digest: sha256
  expiration: "+365d"

# etcd client sensu-backend details:
etcd_client_sensu_backend:
  curve: secp256r1
  digest: sha256
  expiration: "+365d"

sensu_root_ca:
  curve: secp521r1
  digest: sha512
  expiration: "+3650d"

sensu_backend:
  curve: secp256r1
  digest: sha256
  expiration: "+365d"
